coverage:
  range: 80..100
  round: down
  precision: 2

  status:
    project:
      default:
        enabled: yes
        target: 90


        threshold: null
        if_not_found: success
        if_ci_failed: failure
    patch:
      default:
        enabled: no