language: csharp
solution: Semester3/Homework5/5.1/5.1.sln
sudo: required
dist: xenial
dotnet: 3.0

before_build:
  - nuget restore Semester3/Homework5/5.1/5.1.sln

build:
  - dotnet build Semester3/Homework5/5.1/5.1.sln

script:
  - dotnet test Semester3/Homework5/5.1/5.1.sln

global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1 