language: csharp
solution: Semester2/Test1/1.1/1.1.sln 
mono: none
dotnet: 2.1

before_build:
  - nuget restore Semester2/Test1/1.1/1.1.sln 

build:
  - dotnet build Semester2/Test1/1.1/1.1.sln 

script:
  - dotnet test Semester2/Test1/1.1/1.1.sln