language: csharp
solution: Semester2/Homework3/3.2/3.2.sln
sudo: false
dotnet: 2.1

before_build:
  - nuget restore Semester2/Homework3/3.2/3.2.sln

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
  - dotnet build Semester2/Homework3/3.2/3.2.sln
  - dotnet test Semester2/Homework3/3.2/3.2.Tests/3.2.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - mono ./tools/SharpCover/SharpCover.exe check
  - bash <(curl -s https://codecov.io/bash) -t 790fed63-e3aa-4964-a215-c9baec799df1