language: csharp
solution: Semester2/Homework6/6.2/6.2.sln
mono: none
dotnet: 2.2

before_build:
  - nuget restore Semester2/Homework6/6.2/6.2.sln

build:
  - dotnet build Semester2/Homework6/6.2/6.2.sln

script:
  - dotnet test Semester2/Homework6/6.2/6.2.sln
