language: csharp
solution: Semester2/Homework6/6.2/6.2.sln
sudo: required
mono: none
dotnet: 2.1

before_build:
  - nuget restore Semester2/Homework6/6.2/6.2.sln

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

build:
  - dotnet build Semester2/Homework6/6.2/6.2.sln

script:
  - dotnet test Semester2/Homework6/6.2/6.2.sln
  - dotnet test Semester2/Homework6/6.2/6.2.Tests/6.2.Tests.csproj/p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - make coverage
  - bash <(curl -s https://codecov.io/bash) -t 790fed63-e3aa-4964-a215-c9baec799df1