image: Visual Studio 2019 Preview
skip_tags: true
configuration: Release

before_build:
  - nuget restore Semester2/Homework7/7.1/7.1.sln

build:
  project: Semester2/Homework7/7.1/7.1.sln

test_script:
  - nunit3-console.exe Semester2/Homework7/7.1/7.1.Tests/obj/Debug/netcoreapp2.1/7.1.Tests.dll --result=7.1.TestsResults.xml;format=AppVeyor