image: Visual Studio 2019 Preview

before_build:
  - nuget restore Semester2/Homework7/7.1/7.1.sln

build:
  project: Semester2/Homework7/7.1/7.1.sln

test_script:
  - dotnet test Semester2/Homework7/7.1/7.1.sln

after_test:
- ps: >-
    $nunitrunner = (Resolve-Path "tools/NUnit.ConsoleRunner.*/tools/nunit3-console.exe").ToString();