image: Visual Studio 2019 Preview

init:
  - git config --global core.autocrlf true

before_build:
  - nuget restore Semester3/Homework1/1.1/1.1.sln

build:
  project: Semester3/Homework1/1.1/1.1.sln

test_script:
  - dotnet test Semester3/Homework1/1.1/1.1.sln