image: Visual Studio 2019 Preview

before_build:
  - nuget restore Semester2/Homework7/7.1/7.1.sln

build:
  project: Semester2/Homework7/7.1/7.1.sln

test_script:
  - nunit3-console.exe emester2/Homework7/7.1/7.1.Tests/7.1.Tests.csproj