image: Visual Studio 2019

init:
  - git config --global core.autocrlf true

before_build:
  - nuget restore Semester3/Homework5/5.1/5.1.sln

build:
  project: Semester3/Homework5/5.1/5.1.sln

test_script:
  - dotnet test Semester3/Homework5/5.1/5.1.sln