image: Visual Studio 2019 Preview

before_build:
  - nuget restore Semester2/Homework7/7.1/7.1.sln

build_script:
  - msbuild Semester2/Homework7/7.1/7.1.sln /p:Configuration=Release /t:Rebuild

test:
  assemblies:
    - '**\*7.1.Tests.dll'