image: Visual Studio 2019 Preview

before_build:
  - nuget restore Semester2/Semester2/4.1/4.1.sln 

build:
  project: Semester2/Semester2/4.1/4.1.sln 

test_script:
  - dotnet test Semester2/Semester2/4.1/4.1.sln 