image: Visual Studio 2019 Preview

before_build:
  - nuget restore Semester2/Homework7/7.2/7.2.sln

build:
  project: Semester2/Homework7/7.2/7.2.sln

test_script:
  - dotnet test Semester2/Homework7/7.2/7.2.sln