image: Visual Studio 2019 Preview

before_build:
  - nuget restore Semester2/Test2/2.1/2.1.sln 

build:
  project: Semester2/Test2/2.1/2.1.sln 

test_script:
  - dotnet test Semester2/Test2/2.1/2.1.sln 