image: Visual Studio 2019

init:
  - git config --global core.autocrlf true

before_build:
  - nuget restore Semester4/Homework1/1.5/1.5.sln

build:
  project: Semester4/Homework1/1.5/1.5.sln

test_script:
  - dotnet test Semester4/Homework1/1.5/1.5.sln
