image: Visual Studio 2019 Preview

init:
  - git config --global core.autocrlf true

before_build:
  - nuget restore Semester2/Homework8/8.1/8.1.sln

build:
  project: Semester2/Homework8/8.1/8.1.sln

test_script:
  - dotnet test Semester2/Homework8/8.1/8.1.sln